// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Document = 2,
  ObjectTypeDefinition = 3,
  TypeKeyword = 4,
  type = 5,
  NamedTypeDeclaration = 6,
  FieldsDefinition = 7,
  ValueDefinition = 9,
  ValueName = 10,
  Type = 12,
  NamedType = 13,
  GenericType = 15,
  ArrayType = 17,
  Number = 18,
  String = 19
