// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_name = {__proto__:null,type:10}
export const parser = LRParser.deserialize({
  version: 14,
  states: "'bO]QPOOObQQO'#C_Q]QPOOOOQO'#C`'#C`OOQO'#Cr'#CrOOQO'#Cb'#CbOgQPO,58yOOQO-E6p-E6pOoQPO'#DOOOQO'#Cc'#CcOOQO1G.e1G.eOtQPO1G.eOOQO'#Cf'#CfOyQPO'#CeOOQO'#Cs'#CsO!RQPO,59jOOQO7+$P7+$PO!ZQPO,59PO!lQPO,59POOQO-E6q-E6qOOQO1G/U1G/UOOQO'#Ci'#CiO!qQPO'#ChOOQO'#Cn'#CnOOQO'#Co'#CoOOQO'#Ch'#ChO#VQPO'#DQO#eQPO1G.kO!ZQPO1G.kO!ZQPO,59VOOQO'#Cu'#CuO#pQPO,59XO!ZQPO'#CvO$RQPO,59lOOQO7+$V7+$VO$aQPO7+$VO$lQQO'#DRO$tQQO'#ChO%SQPO1G.qOOQO-E6s-E6sOOQO,59b,59bOOQO-E6t-E6tOOQO<<Gq<<GqO!ZQPO'#CtO%XQQO,59mO%aQQO,59XOOQO7+$]7+$]OOQO,59`,59`OOQO-E6r-E6r",
  stateData: "%l~OmOSnOSPOS~OTRO~OpTO~OWWOqZO~Oo[O~OWWO~OZaOsbO~OedOo[O~OWWOoeOxgOyhOzhO~OZlO~O`mOwnOd[Xe[Xo[X{[X~OdpOetXotX{tX~O{rOeXioXi~OwnOdaaeaaoaa{aa~OdpOetaota{ta~O{zOeXqoXq~Ov{O^uX~O`mOwnO^[Xv[X~O^!OO~Ov{O^ua~OwnO^aavaa~O",
  goto: "$VvPPPw{P!P!SP!a!eP!i!vP!YP!Y!Y!YPP#P#V#]#c#mPPPPPPP#sP#|$STSOQTPOQRUPQYUQ`ZZialmp{T^W_T]W_SjalQtmQxpR!P{UfalpTum{QQORVQQ_WRc_Q|tR!Q|QofSwo}R}uQqjRyq_XUZalmp{QkaRslRvm",
  nodeNames: "⚠ Comment Document ObjectTypeDefinition TypeKeyword type NamedTypeDeclaration FieldsDefinition { ValueDefinition ValueName : Type NamedType > GenericType < ArrayType Number String | }",
  maxTerm: 43,
  skippedNodes: [0,1],
  repeatNodeCount: 5,
  tokenData: "+S~RpX^#Vpq#Vrs#zst%twx&]xy(Vyz(V|}([}!O(c!P!Q(|!Q![(i![!])S!]!^)X!^!_)^!_!`)c!`!a)h!a!b)m!c!})r!}#O*V#R#S)r#T#o*b#o#p*s#p#q*x#q#r*}#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#[Ym~X^#Vpq#V#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#}XOY#zYZ$jZr#zrs$js#O#z#O#P$o#P;'S#z;'S;=`%n<%lO#z~$oOy~~$rRO;'S#z;'S;=`${;=`O#z~%OYOY#zYZ$jZr#zrs$js#O#z#O#P$o#P;'S#z;'S;=`%n;=`<%l#z<%lO#z~%qP;=`<%l#z~%ySP~OY%tZ;'S%t;'S;=`&V<%lO%t~&YP;=`<%l%t~&`XOY&]YZ&{Zw&]wx&{x#O&]#O#P'Q#P;'S&];'S;=`(P<%lO&]~'QOz~~'TRO;'S&];'S;=`'^;=`O&]~'aYOY&]YZ&{Zw&]wx&{x#O&]#O#P'Q#P;'S&];'S;=`(P;=`<%l&]<%lO&]~(SP;=`<%l&]~([On~R(cOvQ{P~(fP!Q![(i~(nQx~!O!P(t!Q![(i~(yPx~!Q![(t~)PP!P!Q%t~)XOZ~P)^O{P~)cO`~~)hOq~~)mO^~~)rOs~R)ySpQoP!Q![)r!c!})r#R#S)r#T#o)r~*YP#P#Q*]~*bOw~P*gSoP!Q![*b!c!}*b#R#S*b#T#o*b~*xOW~~*}Od~~+SOe~",
  tokenizers: [0, 1],
  topRules: {"Document":[0,2]},
  specialized: [{term: 31, get: (value) => spec_name[value] || -1}],
  tokenPrec: 0
})
